server:
  port: 8081
spring:
  application:
    name: usuario-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: MICROSERVICEBD
    password: microservicebd
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true