server:
    port: 8082
spring:
    application:
        name: usuario-service
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:XE
        username: MICROSERVICEBD
        password: microservicebd
        driver-class-name: oracle.jdbc.OracleDriver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
             hibernate:
                format_sql: true
        zipkin: http://localhost:9411
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true

resilience4j.circuitbreaker:
    instances:
        vehiculosCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
        motosCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
        todosCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10