server:
    port: 8083
spring:
    application:
        name: vehiculo-service
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:XE
        username: MICROSERVICEBD
        password: microservicebd
        driver-class-name: oracle.jdbc.OracleDriver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
             hibernate:
                format_sql: true
        zipkin: http://localhost:9411
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true        