-- USER SQL
CREATE USER "MICROSERVICEBD" IDENTIFIED BY "microservicebd"  ;

-- QUOTAS

-- ROLES
GRANT "CONNECT" TO "MICROSERVICEBD" ;
GRANT "RESOURCE" TO "MICROSERVICEBD" ;

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO "MICROSERVICEBD" ;
GRANT CREATE VIEW TO "MICROSERVICEBD" ;
GRANT CREATE TABLE TO "MICROSERVICEBD" ;
GRANT CREATE SEQUENCE TO "MICROSERVICEBD" ;
GRANT CREATE PROCEDURE TO "MICROSERVICEBD" ;

--////////////////////////////////////////////////////////////////////

CREATE SEQUENCE USUARIO_INC START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE VEHICULO_INC START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE MOTO_INC START WITH 1 INCREMENT BY 1 NOCACHE;

SELECT*FROM USUARIOS;

SELECT*FROM VEHICULOS;