server:
    port: 8082
spring:
    cloud:
        config:
            server:
                git:
                    default-label: eureka
                    uri: https://github.com/Samuelito888/microservicios-beginner
                    search-paths: config-data
    application:
        name: config-service